name = "dress-printful-worker"
main = "worker.js"
compatibility_date = "2025-10-08"
workers_dev = true

[build]
command = "echo 'No build step required'"
cwd = "./"
watch_dir = "./"

[dev]
ip = "localhost"
port = 8787
local_protocol = "http"
upstream_protocol = "https"

[env.production]
vars = { ENVIRONMENT = "production" }
routes = ["https://newdress-cgz.pages.dev/api/printful/*"]

[env.staging]
vars = { ENVIRONMENT = "staging" }